//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

namespace TCPSmart.WsAlt
{
    // 
    // Este código fuente fue generado automáticamente por wsdl, Versión=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "SI_BPM_CashOutGuipBinding", Namespace = "urn:bz.bancatlan.bpm:1.0:BPMI037")]
    public partial class SI_BPM_CashOutGuipService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        public String Guido { get; }

        private System.Threading.SendOrPostCallback SI_BPM_CashOutGuipOperationCompleted;

        /// <remarks/>
        public SI_BPM_CashOutGuipService()
        {
            Guido = new Guid().ToString();
            this.Url = TCPUtil.WsAmbientForOperation.URL;

        }

        /// <remarks/>
        public event SI_BPM_CashOutGuipCompletedEventHandler SI_BPM_CashOutGuipCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MT_CashOutGuip_Resp", Namespace = "http://bancatlan.bz/BPMI037/1.0/out/CashOutGuip")]
        public DT_CashOutGuipResponse SI_BPM_CashOutGuip([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://bancatlan.bz/BPMI037/1.0/out/CashOutGuip")] DT_CashOutGuip MT_CashOutGuip_Req)
        {
            object[] results = this.Invoke("SI_BPM_CashOutGuip", new object[] {
                    MT_CashOutGuip_Req});
            return ((DT_CashOutGuipResponse)(results[0]));
        }

        /// <remarks/>
        //public System.IAsyncResult BeginSI_BPM_CashOutGuip(DT_CashOutGuip MT_CashOutGuip_Req, System.AsyncCallback callback, object asyncState)
        //{
        //    return this.BeginInvoke("SI_BPM_CashOutGuip", new object[] {
        //            MT_CashOutGuip_Req}, callback, asyncState);
        //}

        ///// <remarks/>
        //public DT_CashOutGuipResponse EndSI_BPM_CashOutGuip(System.IAsyncResult asyncResult)
        //{
        //    object[] results = this.EndInvoke(asyncResult);
        //    return ((DT_CashOutGuipResponse)(results[0]));
        //}

        /// <remarks/>
        public void SI_BPM_CashOutGuipAsync(DT_CashOutGuip MT_CashOutGuip_Req)
        {
            this.SI_BPM_CashOutGuipAsync(MT_CashOutGuip_Req, null);
        }

        /// <remarks/>
        public void SI_BPM_CashOutGuipAsync(DT_CashOutGuip MT_CashOutGuip_Req, object userState)
        {
            if ((this.SI_BPM_CashOutGuipOperationCompleted == null))
            {
                this.SI_BPM_CashOutGuipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_BPM_CashOutGuipOperationCompleted);
            }
            this.InvokeAsync("SI_BPM_CashOutGuip", new object[] {
                    MT_CashOutGuip_Req}, this.SI_BPM_CashOutGuipOperationCompleted, userState);
        }

        private void OnSI_BPM_CashOutGuipOperationCompleted(object arg)
        {
            if ((this.SI_BPM_CashOutGuipCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_BPM_CashOutGuipCompleted(this, new SI_BPM_CashOutGuipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:bz.bancatlan.bpm:1.0:BPMI037")]
    public partial class DT_CashOutGuip
    {

        private string transaccionIdField;

        private string aplicacionIdField;

        private string paisIdField;

        private string empresaIdField;

        private string regionIdField;

        private string canalIdField;

        private string versionField;

        private string llaveSesionField;

        private string clienteCoreIdField;

        private string usuarioIdField;

        private string tokenField;

        private string dispositivoIdField;

        private DT_identificadorColeccion[] identificadorColeccionField;

        private DT_parametroAdicionalItem[] parametroAdicionalColeccionField;

        private DT_logItem[] logColeccionField;

        private DT_CashOut atmCashOutField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transaccionId
        {
            get
            {
                return this.transaccionIdField;
            }
            set
            {
                this.transaccionIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string aplicacionId
        {
            get
            {
                return this.aplicacionIdField;
            }
            set
            {
                this.aplicacionIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paisId
        {
            get
            {
                return this.paisIdField;
            }
            set
            {
                this.paisIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string empresaId
        {
            get
            {
                return this.empresaIdField;
            }
            set
            {
                this.empresaIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string regionId
        {
            get
            {
                return this.regionIdField;
            }
            set
            {
                this.regionIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string canalId
        {
            get
            {
                return this.canalIdField;
            }
            set
            {
                this.canalIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string llaveSesion
        {
            get
            {
                return this.llaveSesionField;
            }
            set
            {
                this.llaveSesionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clienteCoreId
        {
            get
            {
                return this.clienteCoreIdField;
            }
            set
            {
                this.clienteCoreIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuarioId
        {
            get
            {
                return this.usuarioIdField;
            }
            set
            {
                this.usuarioIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dispositivoId
        {
            get
            {
                return this.dispositivoIdField;
            }
            set
            {
                this.dispositivoIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("identificadorColeccion", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_identificadorColeccion[] identificadorColeccion
        {
            get
            {
                return this.identificadorColeccionField;
            }
            set
            {
                this.identificadorColeccionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("parametroAdicionalItem", typeof(DT_parametroAdicionalItem), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DT_parametroAdicionalItem[] parametroAdicionalColeccion
        {
            get
            {
                return this.parametroAdicionalColeccionField;
            }
            set
            {
                this.parametroAdicionalColeccionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("logItem", typeof(DT_logItem), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DT_logItem[] logColeccion
        {
            get
            {
                return this.logColeccionField;
            }
            set
            {
                this.logColeccionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_CashOut AtmCashOut
        {
            get
            {
                return this.atmCashOutField;
            }
            set
            {
                this.atmCashOutField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:bz.bancatlan.bpm:1.0:BPMI037")]
    public partial class DT_identificadorColeccion
    {

        private string wasField;

        private string piField;

        private string omniCanalField;

        private string reciboField;

        private string numeroTransaccionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string was
        {
            get
            {
                return this.wasField;
            }
            set
            {
                this.wasField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pi
        {
            get
            {
                return this.piField;
            }
            set
            {
                this.piField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string omniCanal
        {
            get
            {
                return this.omniCanalField;
            }
            set
            {
                this.omniCanalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string recibo
        {
            get
            {
                return this.reciboField;
            }
            set
            {
                this.reciboField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroTransaccion
        {
            get
            {
                return this.numeroTransaccionField;
            }
            set
            {
                this.numeroTransaccionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:bz.bancatlan.bpm:1.0:BPMI037")]
    public partial class DT_CashOutResponse
    {

        private string f0Field;

        private string f1Field;

        private string f2Field;

        private string f3Field;

        private string f4Field;

        private string f7Field;

        private string f11Field;

        private string f19Field;

        private string f25Field;

        private string f32Field;

        private string f35Field;

        private string f37Field;

        private string f38Field;

        private string f39Field;

        private string f41Field;

        private string f42Field;

        private string f49Field;

        private string f63Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F0
        {
            get
            {
                return this.f0Field;
            }
            set
            {
                this.f0Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F1
        {
            get
            {
                return this.f1Field;
            }
            set
            {
                this.f1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F2
        {
            get
            {
                return this.f2Field;
            }
            set
            {
                this.f2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F3
        {
            get
            {
                return this.f3Field;
            }
            set
            {
                this.f3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F4
        {
            get
            {
                return this.f4Field;
            }
            set
            {
                this.f4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F7
        {
            get
            {
                return this.f7Field;
            }
            set
            {
                this.f7Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F11
        {
            get
            {
                return this.f11Field;
            }
            set
            {
                this.f11Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F19
        {
            get
            {
                return this.f19Field;
            }
            set
            {
                this.f19Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F25
        {
            get
            {
                return this.f25Field;
            }
            set
            {
                this.f25Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F32
        {
            get
            {
                return this.f32Field;
            }
            set
            {
                this.f32Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F35
        {
            get
            {
                return this.f35Field;
            }
            set
            {
                this.f35Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F37
        {
            get
            {
                return this.f37Field;
            }
            set
            {
                this.f37Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F38
        {
            get
            {
                return this.f38Field;
            }
            set
            {
                this.f38Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F39
        {
            get
            {
                return this.f39Field;
            }
            set
            {
                this.f39Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F41
        {
            get
            {
                return this.f41Field;
            }
            set
            {
                this.f41Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F42
        {
            get
            {
                return this.f42Field;
            }
            set
            {
                this.f42Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F49
        {
            get
            {
                return this.f49Field;
            }
            set
            {
                this.f49Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F63
        {
            get
            {
                return this.f63Field;
            }
            set
            {
                this.f63Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:bz.bancatlan.bpm:1.0:BPMI037")]
    public partial class DT_estado
    {

        private string codigoField;

        private string descripcionField;

        private string detalleTecnicoField;

        private string tipoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string detalleTecnico
        {
            get
            {
                return this.detalleTecnicoField;
            }
            set
            {
                this.detalleTecnicoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:bz.bancatlan.bpm:1.0:BPMI037")]
    public partial class DT_CashOutGuipResponse
    {

        private DT_estado estadoField;

        private DT_CashOutResponse atmCashOutField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_estado Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_CashOutResponse AtmCashOut
        {
            get
            {
                return this.atmCashOutField;
            }
            set
            {
                this.atmCashOutField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:bz.bancatlan.bpm:1.0:BPMI037")]
    public partial class DT_CashOut
    {

        private string f0Field;

        private string f1Field;

        private string f2Field;

        private string f3Field;

        private string f4Field;

        private string f7Field;

        private string f11Field;

        private string f19Field;

        private string f25Field;

        private string f32Field;

        private string f35Field;

        private string f37Field;

        private string f38Field;

        private string f41Field;

        private string f42Field;

        private string f43Field;

        private string f49Field;

        private string f63Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F0
        {
            get
            {
                return this.f0Field;
            }
            set
            {
                this.f0Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F1
        {
            get
            {
                return this.f1Field;
            }
            set
            {
                this.f1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F2
        {
            get
            {
                return this.f2Field;
            }
            set
            {
                this.f2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F3
        {
            get
            {
                return this.f3Field;
            }
            set
            {
                this.f3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F4
        {
            get
            {
                return this.f4Field;
            }
            set
            {
                this.f4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F7
        {
            get
            {
                return this.f7Field;
            }
            set
            {
                this.f7Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F11
        {
            get
            {
                return this.f11Field;
            }
            set
            {
                this.f11Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F19
        {
            get
            {
                return this.f19Field;
            }
            set
            {
                this.f19Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F25
        {
            get
            {
                return this.f25Field;
            }
            set
            {
                this.f25Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F32
        {
            get
            {
                return this.f32Field;
            }
            set
            {
                this.f32Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F35
        {
            get
            {
                return this.f35Field;
            }
            set
            {
                this.f35Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F37
        {
            get
            {
                return this.f37Field;
            }
            set
            {
                this.f37Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F38
        {
            get
            {
                return this.f38Field;
            }
            set
            {
                this.f38Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F41
        {
            get
            {
                return this.f41Field;
            }
            set
            {
                this.f41Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F42
        {
            get
            {
                return this.f42Field;
            }
            set
            {
                this.f42Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F43
        {
            get
            {
                return this.f43Field;
            }
            set
            {
                this.f43Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F49
        {
            get
            {
                return this.f49Field;
            }
            set
            {
                this.f49Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string F63
        {
            get
            {
                return this.f63Field;
            }
            set
            {
                this.f63Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:bz.bancatlan.bpm:1.0:BPMI037")]
    public partial class DT_logItem
    {

        private string identificadorWasField;

        private string identificadorPiField;

        private string identificadorOmniCanalField;

        private string identificadorReciboField;

        private string identificadorNumeroTransaccionField;

        private string aplicacionIdField;

        private string canalIdField;

        private string ambienteIdField;

        private string transaccionIdField;

        private string accionField;

        private string tipoField;

        private string fechaField;

        private string horaField;

        private string fechaSistemaField;

        private string horaSistemaField;

        private string auxiliar1Field;

        private string auxiliar2Field;

        private DT_parametroAdicionalItem[] parametroAdicionalColeccionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string identificadorWas
        {
            get
            {
                return this.identificadorWasField;
            }
            set
            {
                this.identificadorWasField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificadorPi
        {
            get
            {
                return this.identificadorPiField;
            }
            set
            {
                this.identificadorPiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificadorOmniCanal
        {
            get
            {
                return this.identificadorOmniCanalField;
            }
            set
            {
                this.identificadorOmniCanalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificadorRecibo
        {
            get
            {
                return this.identificadorReciboField;
            }
            set
            {
                this.identificadorReciboField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificadorNumeroTransaccion
        {
            get
            {
                return this.identificadorNumeroTransaccionField;
            }
            set
            {
                this.identificadorNumeroTransaccionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string aplicacionId
        {
            get
            {
                return this.aplicacionIdField;
            }
            set
            {
                this.aplicacionIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string canalId
        {
            get
            {
                return this.canalIdField;
            }
            set
            {
                this.canalIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ambienteId
        {
            get
            {
                return this.ambienteIdField;
            }
            set
            {
                this.ambienteIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transaccionId
        {
            get
            {
                return this.transaccionIdField;
            }
            set
            {
                this.transaccionIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accion
        {
            get
            {
                return this.accionField;
            }
            set
            {
                this.accionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hora
        {
            get
            {
                return this.horaField;
            }
            set
            {
                this.horaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaSistema
        {
            get
            {
                return this.fechaSistemaField;
            }
            set
            {
                this.fechaSistemaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string horaSistema
        {
            get
            {
                return this.horaSistemaField;
            }
            set
            {
                this.horaSistemaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string auxiliar1
        {
            get
            {
                return this.auxiliar1Field;
            }
            set
            {
                this.auxiliar1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string auxiliar2
        {
            get
            {
                return this.auxiliar2Field;
            }
            set
            {
                this.auxiliar2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("parametroAdicionalItem", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DT_parametroAdicionalItem[] parametroAdicionalColeccion
        {
            get
            {
                return this.parametroAdicionalColeccionField;
            }
            set
            {
                this.parametroAdicionalColeccionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:bz.bancatlan.bpm:1.0:BPMI037")]
    public partial class DT_parametroAdicionalItem
    {

        private string lineaField;

        private string tipoRegistroField;

        private string valorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string linea
        {
            get
            {
                return this.lineaField;
            }
            set
            {
                this.lineaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoRegistro
        {
            get
            {
                return this.tipoRegistroField;
            }
            set
            {
                this.tipoRegistroField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void SI_BPM_CashOutGuipCompletedEventHandler(object sender, SI_BPM_CashOutGuipCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_BPM_CashOutGuipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SI_BPM_CashOutGuipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public DT_CashOutGuipResponse Result
        {
            get
            {
                try
                {
                    return ((DT_CashOutGuipResponse)(this.results[0]));
                }
                catch (Exception)
                {

                    return null;
                }
                //this.RaiseExceptionIfNecessary();               
            }
        }
    }
}
